apiVersion: v1
kind: ConfigMap
metadata:
  name: dentalhelp-config
  namespace: dentalhelp
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
